/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include <string.h>
#include <thrift.h>
#include <thrift_application_exception.h>
#include "scribe.h"

gboolean
scribe_if_log (scribeIf *iface, ResultCode* _return, const GPtrArray * messages, GError **error)
{
  return SCRIBE_IF_GET_INTERFACE (iface)->log (iface, _return, messages, error);
}

GType
scribe_if_get_type (void)
{
  static GType type = 0;
  if (type == 0)
  {
    static const GTypeInfo type_info =
    {
      sizeof (scribeIfInterface),
      NULL,  /* base_init */
      NULL  /* base_finalize */
    };
    type = g_type_register_static (G_TYPE_INTERFACE,
                                   "scribeIf",
                                   &type_info, 0);
  }
  return type;
}

static void 
scribe_if_interface_init (scribeIfInterface *iface);

G_DEFINE_TYPE_WITH_CODE (scribeClient, scribe_client,
                       G_TYPE_OBJECT, 
                         G_IMPLEMENT_INTERFACE (TYPE_SCRIBE_IF,
                                                scribe_if_interface_init));

enum _scribeClientProperties
{
  PROP_0,
  PROP_SCRIBE_CLIENT_INPUT_PROTOCOL,
  PROP_SCRIBE_CLIENT_OUTPUT_PROTOCOL
};

void
scribe_client_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec)
{
  scribeClient *client = SCRIBE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_SCRIBE_CLIENT_INPUT_PROTOCOL:
      client->input_protocol = g_value_get_object (value);
      break;
    case PROP_SCRIBE_CLIENT_OUTPUT_PROTOCOL:
      client->output_protocol = g_value_get_object (value);
      break;
  }
}

void
scribe_client_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec)
{
  scribeClient *client = SCRIBE_CLIENT (object);

  THRIFT_UNUSED_VAR (pspec);

  switch (property_id)
  {
    case PROP_SCRIBE_CLIENT_INPUT_PROTOCOL:
      g_value_set_object (value, client->input_protocol);
      break;
    case PROP_SCRIBE_CLIENT_OUTPUT_PROTOCOL:
      g_value_set_object (value, client->output_protocol);
      break;
  }
}

gboolean scribe_client_send_log (scribeIf * iface, const GPtrArray * messages, GError ** error)
{
  gint32 cseqid = 0;
  ThriftProtocol * protocol = SCRIBE_CLIENT (iface)->output_protocol;

  if (thrift_protocol_write_message_begin (protocol, "Log", T_CALL, cseqid, error) < 0)
    return FALSE;

  {
    gint32 ret;
    gint32 xfer = 0;

    
    if ((ret = thrift_protocol_write_struct_begin (protocol, "Log_args", error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_begin (protocol, "messages", T_LIST, 1, error)) < 0)
      return 0;
    xfer += ret;
    {
      if ((ret = thrift_protocol_write_list_begin (protocol, T_STRUCT, (gint32) messages->len, error)) < 0)
        return 0;
      xfer += ret;
      guint i;
      for (i=0; i<messages->len; i++)
      {
        if ((ret = thrift_struct_write (THRIFT_STRUCT (g_ptr_array_index ((GPtrArray *) messages, i)), protocol, error)) < 0)
          return 0;
        xfer += ret;

      }
      if ((ret = thrift_protocol_write_list_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }
    if ((ret = thrift_protocol_write_field_end (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_field_stop (protocol, error)) < 0)
      return 0;
    xfer += ret;
    if ((ret = thrift_protocol_write_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_write_message_end (protocol, error) < 0)
    return FALSE;
  if (!thrift_transport_flush (protocol->transport, error))
    return FALSE;
  if (!thrift_transport_write_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean scribe_client_recv_log (scribeIf * iface, ResultCode* _return, GError ** error)
{

  gint32 rseqid;
  gchar * fname;
  ThriftMessageType mtype;
  ThriftProtocol * protocol = SCRIBE_CLIENT (iface)->input_protocol;

  if (thrift_protocol_read_message_begin (protocol, &fname, &mtype, &rseqid, error) < 0)
  {
    if (fname) g_free (fname);
    return FALSE;
  }

  if (mtype == T_EXCEPTION) {
    if (fname) g_free (fname);
    ThriftApplicationException *xception = g_object_new (THRIFT_TYPE_APPLICATION_EXCEPTION, NULL);
    thrift_struct_read (THRIFT_STRUCT (xception), protocol, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, xception->type, "application error: %s", xception->message);
    g_object_unref (xception);
    return FALSE;
  } else if (mtype != T_REPLY) {
    if (fname) g_free (fname);
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, NULL);
    thrift_transport_read_end (protocol->transport, NULL);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_INVALID_MESSAGE_TYPE, "invalid message type %d, expected T_REPLY", mtype);
    return FALSE;
  } else if (strncmp (fname, "Log", 3) != 0) {
    thrift_protocol_skip (protocol, T_STRUCT, NULL);
    thrift_protocol_read_message_end (protocol, error);
    thrift_transport_read_end (protocol->transport, error);
    g_set_error (error, THRIFT_APPLICATION_EXCEPTION_ERROR, THRIFT_APPLICATION_EXCEPTION_ERROR_WRONG_METHOD_NAME, "wrong method name %s, expected Log", fname);
    if (fname) g_free (fname);
    return FALSE;
  }
  if (fname) g_free (fname);

  {
    gint32 ret;
    gint32 xfer = 0;
    gchar *name;
    ThriftType ftype;
    gint16 fid;
    guint32 len = 0;
    gpointer data = NULL;
    

    /* satisfy -Wall in case these aren't used */
    THRIFT_UNUSED_VAR (len);
    THRIFT_UNUSED_VAR (data);

    /* read the struct begin marker */
    if ((ret = thrift_protocol_read_struct_begin (protocol, &name, error)) < 0)
    {
      if (name) g_free (name);
      return 0;
    }
    xfer += ret;
    if (name) g_free (name);

    /* read the struct fields */
    while (1)
    {
      /* read the beginning of a field */
      if ((ret = thrift_protocol_read_field_begin (protocol, &name, &ftype, &fid, error)) < 0)
      {
        if (name) g_free (name);
        return 0;
      }
      xfer += ret;
      if (name) g_free (name);

      /* break if we get a STOP field */
      if (ftype == T_STOP)
      {
        break;
      }

      switch (fid)
      {
        case 0:
          if (ftype == T_I32)
          {
            gint32 ecast0;
            if ((ret = thrift_protocol_read_i32 (protocol, &ecast0, error)) < 0)
              return 0;
            xfer += ret;
            *_return = (ResultCode)ecast0;
          } else {
            if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
              return 0;
            xfer += ret;
          }
          break;
        default:
          if ((ret = thrift_protocol_skip (protocol, ftype, error)) < 0)
            return 0;
          xfer += ret;
          break;
      }
      if ((ret = thrift_protocol_read_field_end (protocol, error)) < 0)
        return 0;
      xfer += ret;
    }

    if ((ret = thrift_protocol_read_struct_end (protocol, error)) < 0)
      return 0;
    xfer += ret;

  }

  if (thrift_protocol_read_message_end (protocol, error) < 0)
    return FALSE;

  if (!thrift_transport_read_end (protocol->transport, error))
    return FALSE;

  return TRUE;
}

gboolean scribe_client_log (scribeIf * iface, ResultCode* _return, const GPtrArray * messages, GError ** error)
{
  if (!scribe_client_send_log (iface, messages, error))
    return FALSE;
  if (!scribe_client_recv_log (iface, _return, error))
    return FALSE;
  return TRUE;
}

static void
scribe_if_interface_init (scribeIfInterface *iface)
{
  iface->log = scribe_client_log;
}

static void
scribe_client_init (scribeClient *client)
{
  client->input_protocol = NULL;
  client->output_protocol = NULL;
}

static void
scribe_client_class_init (scribeClientClass *cls)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (cls);
  GParamSpec *param_spec;

  gobject_class->set_property = scribe_client_set_property;
  gobject_class->get_property = scribe_client_get_property;

  param_spec = g_param_spec_object ("input_protocol",
                                    "input protocol (construct)",
                                    "Set the client input protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SCRIBE_CLIENT_INPUT_PROTOCOL, param_spec);

  param_spec = g_param_spec_object ("output_protocol",
                                    "output protocol (construct)",
                                    "Set the client output protocol",
                                    THRIFT_TYPE_PROTOCOL,
                                    G_PARAM_READWRITE);
  g_object_class_install_property (gobject_class,
                                   PROP_SCRIBE_CLIENT_OUTPUT_PROTOCOL, param_spec);
}

