/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef SCRIBE_H
#define SCRIBE_H

#include "scribe_types.h"
#include "facebook_service.h"

/* scribe service interface */
typedef struct _scribeIf scribeIf;  /* dummy object */

struct _scribeIfInterface
{
  GTypeInterface parent;

  gboolean (*log) (scribeIf *iface, ResultCode* _return, const GPtrArray * messages, GError **error);
};
typedef struct _scribeIfInterface scribeIfInterface;

GType scribe_if_get_type (void);
#define TYPE_SCRIBE_IF (scribe_if_get_type())
#define SCRIBE_IF(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCRIBE_IF, scribeIf))
#define IS_SCRIBE_IF(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj, TYPE_SCRIBE_IF))
#define SCRIBE_IF_GET_INTERFACE(inst) (G_TYPE_INSTANCE_GET_INTERFACE ((inst), TYPE_SCRIBE_IF, scribeIfInterface))

gboolean scribe_if_log (scribeIf *iface, ResultCode* _return, const GPtrArray * messages, GError **error);

/* scribe service client */
struct _scribeClient
{
  GObject parent;

  ThriftProtocol *input_protocol;
  ThriftProtocol *output_protocol;
};
typedef struct _scribeClient scribeClient;

struct _scribeClientClass
{
  GObjectClass parent;
};
typedef struct _scribeClientClass scribeClientClass;

GType scribe_client_get_type (void);
#define TYPE_SCRIBE_CLIENT (scribe_client_get_type())
#define SCRIBE_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SCRIBE_CLIENT, scribeClient))
#define SCRIBE_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), TYPE_SCRIBE_CLIENT, scribeClientClass))
#define SCRIBE_IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SCRIBE_CLIENT))
#define SCRIBE_IS_CLIENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_SCRIBE_CLIENT))
#define SCRIBE_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SCRIBE_CLIENT, scribeClientClass))

gboolean scribe_client_log (scribeIf * iface, ResultCode* _return, const GPtrArray * messages, GError ** error);
gboolean scribe_client_send_log (scribeIf * iface, const GPtrArray * messages, GError ** error);
gboolean scribe_client_recv_log (scribeIf * iface, ResultCode* _return, GError ** error);

#endif /* SCRIBE_H */
